# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-25 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('SAV', 'SAVVY'), ('PRO', 'PROFICIENT'), ('EXP', 'EXPERT')], max_length=3)),
                ('question_num', models.IntegerField()),
                ('question_text', models.TextField(max_length=1000)),
                ('evaluated_skills', models.CharField(max_length=255)),
                ('answer_advice', models.TextField(blank=True, max_length=1000)),
                ('answer_pro_tip', models.TextField(blank=True, max_length=1000)),
                ('answer_example', models.TextField(blank=True, max_length=1000)),
                ('specialist_full_name', models.CharField(blank=True, max_length=255)),
                ('specialist_position', models.CharField(blank=True, max_length=255)),
                ('specialist_company', models.CharField(blank=True, max_length=255)),
                ('specialist_avatar', models.ImageField(blank=True, null=True, upload_to='static/media/images/avatars/', verbose_name='specialist_avatar')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='interviewqa',
            unique_together=set([('level', 'question_num')]),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='interviewQA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interview_prep_app.InterviewQA'),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='interviewanswer',
            unique_together=set([('user', 'interviewQA')]),
        ),
    ]
