# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-25 16:50
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True, max_length=1000)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('company', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='typeguser',
            name='facebookUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typeguser',
            name='linkedInUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typeguser',
            name='mediumUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typeguser',
            name='siteUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailbaseduser',
            name='user_type',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='position',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
