# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-02 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_typeguser_top_skill_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeguser',
            name='top_skill_1',
        ),
    ]
