# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-02 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_typeguser_top_skill_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeguser',
            name='skill_top_val1',
        ),
        migrations.RemoveField(
            model_name='typeguser',
            name='skill_top_val2',
        ),
        migrations.RemoveField(
            model_name='typeguser',
            name='skill_top_val3',
        ),
        migrations.AddField(
            model_name='typeguser',
            name='top_skill_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='typeguser',
            name='top_skill_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
