# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-02 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_auto_20161002_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='id',
        ),
        migrations.RemoveField(
            model_name='typeguser',
            name='top_skill_1',
        ),
        migrations.RemoveField(
            model_name='typeguser',
            name='top_skill_2',
        ),
        migrations.RemoveField(
            model_name='typeguser',
            name='top_skill_3',
        ),
        migrations.AddField(
            model_name='typeguser',
            name='skill_top_val1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_top_val1', to='account_app.Skills'),
        ),
        migrations.AddField(
            model_name='typeguser',
            name='skill_top_val2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_top_val2', to='account_app.Skills'),
        ),
        migrations.AddField(
            model_name='typeguser',
            name='skill_top_val3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_top_val3', to='account_app.Skills'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
