# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-03 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0008_specialization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
