# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-03 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0009_delete_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertisearea',
            name='id',
        ),
        migrations.AlterField(
            model_name='expertisearea',
            name='name',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
